export type Role='owner'|'manager'|'cashier'|'waiter'|'kitchen'|'rider'|'accountant'|'viewer';
export interface User{id:string;name:string;email:string;role:Role;permissions:string[]}
export interface MenuItem{_id:string;name:string;description?:string;sku?:string;price:number;cost:number;category:{_id:string;name:string}|string;kitchenStation:string;preparationTime:number;available:boolean;modifierGroups?:{name:string;required?:boolean;multiple?:boolean;options:{_id:string;label:string;priceAdjustment:number}[]}[];addons?:{_id:string;label:string;priceAdjustment:number}[]}
export interface Category{_id:string;name:string;icon?:string;displayOrder?:number;active?:boolean}
export interface AddOn{_id:string;label:string;priceAdjustment:number;category?:Category|string;active:boolean}
export interface Deal{_id:string;name:string;description?:string;price:number;items:{menuItem:MenuItem|string;quantity:number}[];active:boolean}
export interface PromoCode{_id:string;code:string;label?:string;discountType:'fixed'|'percentage';discount:number;active:boolean}
export interface InventoryItem{_id:string;name:string;sku?:string;unit:string;currentStock:number;minimumStock:number;costPrice:number}
export interface Recipe{_id:string;menuItem:MenuItem|string;ingredients:{item:InventoryItem|string;quantity:number}[];costPerServing:number}
export interface CartLine{id:string;menuItem:string;name:string;quantity:number;unitPrice:number;station:string;modifiers:{label:string;priceAdjustment:number}[];notes?:string}
export interface Order{_id:string;orderNumber:string;type:'dine-in'|'takeaway'|'delivery'|'foodpanda';status:string;table?:any;customer?:any;customerName?:string;customerPhone?:string;guests?:number;deliveryAddress?:string;rider?:any;items:any[];subtotal:number;discount:number;tax:number;serviceCharge:number;total:number;payments:any[];timeline:any[];createdAt:string;staff?:any;notes?:string}
export interface Paged<T>{data:T[];meta:{page:number;limit:number;total:number;pages:number}}
