import {Category,MenuItem} from '../models/Catalog.js';import {AppError,asyncHandler} from '../utils/errors.js';import {categoryDto,menuItemDto,queueIntegrationEvent} from '../integration/integrationEvents.js';

const categoryPayload=async(category:any)=>categoryDto(category);
const itemPayload=async(item:any)=>{const category:any=await Category.findById(item.category).lean();return menuItemDto(item,category?.externalId);};
export const createCategory=asyncHandler(async(req:any,res:any)=>{const data:any=await Category.create(req.body);await queueIntegrationEvent('CATEGORY_CREATED',await categoryPayload(data));res.status(201).json({data});});
export const updateCategory=asyncHandler(async(req:any,res:any)=>{const data:any=await Category.findById(req.params.id);if(!data)throw new AppError(404,'Record not found');Object.assign(data,req.body);await data.save();await queueIntegrationEvent('CATEGORY_UPDATED',await categoryPayload(data));res.json({data});});
export const removeCategory=asyncHandler(async(req:any,res:any)=>{const data:any=await Category.findByIdAndDelete(req.params.id);if(!data)throw new AppError(404,'Record not found');await queueIntegrationEvent('CATEGORY_DELETED',{...(await categoryPayload(data)),deleted:true,active:false});res.status(204).end();});
export const createMenuItem=asyncHandler(async(req:any,res:any)=>{const data:any=await MenuItem.create(req.body);await queueIntegrationEvent('MENU_ITEM_CREATED',await itemPayload(data));res.status(201).json({data});});
export const updateMenuItem=asyncHandler(async(req:any,res:any)=>{const data:any=await MenuItem.findById(req.params.id);if(!data)throw new AppError(404,'Record not found');const availabilityOnly=Object.keys(req.body).every(key=>key==='available');Object.assign(data,req.body);await data.save();await queueIntegrationEvent(availabilityOnly?'MENU_AVAILABILITY_UPDATED':'MENU_ITEM_UPDATED',await itemPayload(data));res.json({data});});
export const removeMenuItem=asyncHandler(async(req:any,res:any)=>{const data:any=await MenuItem.findByIdAndDelete(req.params.id);if(!data)throw new AppError(404,'Record not found');await queueIntegrationEvent('MENU_ITEM_DELETED',{...(await itemPayload(data)),deleted:true,available:false});res.status(204).end();});
