import {z} from 'zod';import {Category,MenuItem} from '../models/Catalog.js';import {Customer} from '../models/Operations.js';import {Order} from '../models/Order.js';import {IntegrationEvent,IntegrationInboundEvent} from '../models/IntegrationEvent.js';import {env} from '../config/env.js';import {categoryDto,menuItemDto,queueIntegrationEvent} from '../integration/integrationEvents.js';import {isFreshTimestamp,verifySignature} from '../integration/webhookSigning.js';import {AppError,asyncHandler} from '../utils/errors.js';

const incomingOrder=z.object({externalOrderId:z.string().min(1).max(200),orderType:z.enum(['pickup','takeaway','delivery']).default('pickup'),customer:z.object({name:z.string().min(1).max(200),phone:z.string().min(1).max(80),email:z.string().email().optional(),address:z.string().max(1000).optional()}).optional(),deliveryAddress:z.string().max(1000).optional(),notes:z.string().max(2000).optional(),paymentMethod:z.enum(['cash','card','transfer','credit','wallet']).optional(),items:z.array(z.object({externalMenuItemId:z.string().uuid(),quantity:z.coerce.number().int().min(1).max(100),notes:z.string().max(1000).optional(),modifiers:z.array(z.object({label:z.string().min(1).max(200)})).optional(),price:z.number().optional()})).min(1)});

export const verifyOrangeWebhook=asyncHandler(async(req:any,_res:any,next:any)=>{if(!env.INTEGRATION_ENABLED||!env.ORANGE_WEBSITE_SYNC_SECRET)throw new AppError(503,'Orange Website integration is not enabled');const timestamp=String(req.get('x-integration-timestamp')||'');const signature=String(req.get('x-integration-signature')||'');if(!isFreshTimestamp(timestamp,env.INTEGRATION_REPLAY_WINDOW_SECONDS)||!signature||!verifySignature(timestamp,req.rawBody||JSON.stringify(req.body),signature,env.ORANGE_WEBSITE_SYNC_SECRET))throw new AppError(401,'Invalid or expired integration signature');next();});

const authoritativeModifiers=(item:any,requested:any[]=[])=>(requested||[]).map(request=>{const candidates=[...(item.modifierGroups||[]).flatMap((group:any)=>group.options||[]),...(item.variants||[]),...(item.addons||[])];const found=candidates.find((candidate:any)=>candidate.label===request.label);if(!found)throw new AppError(422,`Modifier ${request.label} is not valid for ${item.name}`);return {label:found.label,priceAdjustment:Number(found.priceAdjustment||0)};});
export const receiveOrangeOrder=asyncHandler(async(req:any,res:any)=>{const eventId=String(req.get('x-integration-event-id')||'');if(!eventId)throw new AppError(422,'x-integration-event-id is required');const input=incomingOrder.parse(req.body);const existing:any=await Order.findOne({source:'orange-website',externalOrderId:input.externalOrderId});if(existing)return res.status(200).json({data:existing,idempotent:true});const received=await IntegrationInboundEvent.exists({eventId});if(received)throw new AppError(409,'Integration event ID was already processed');const lines=[] as any[];for(const requested of input.items){const item:any=await MenuItem.findOne({externalId:requested.externalMenuItemId});if(!item||!item.available)throw new AppError(422,`Menu item ${requested.externalMenuItemId} is unavailable`);const modifiers=authoritativeModifiers(item,requested.modifiers);lines.push({menuItem:item._id,name:item.name,quantity:requested.quantity,unitPrice:item.price,modifiers,notes:requested.notes,station:item.kitchenStation});}
  let customer:any; if(input.customer){customer=await Customer.findOne({phone:input.customer.phone});if(customer){customer.name=input.customer.name;customer.email=input.customer.email||customer.email;customer.address=input.customer.address||customer.address;await customer.save();}else customer=await Customer.create({name:input.customer.name,phone:input.customer.phone,email:input.customer.email,address:input.customer.address});}
  const type=input.orderType==='delivery'?'delivery':'takeaway';let created:any;try{created=await Order.create({source:'orange-website',externalOrderId:input.externalOrderId,type,status:'pending',customer:customer?._id,customerName:input.customer?.name,customerPhone:input.customer?.phone,deliveryAddress:input.deliveryAddress||input.customer?.address,requestedPaymentMethod:input.paymentMethod,notes:input.notes,items:lines,timeline:[{status:'pending'}]});}catch(error:any){if(error?.code===11000){const duplicate=await Order.findOne({source:'orange-website',externalOrderId:input.externalOrderId});return res.status(200).json({data:duplicate,idempotent:true});}throw error;}
  try{await IntegrationInboundEvent.create({eventId,source:'orange-website'});}catch(error:any){if(error?.code!==11000)throw error;}
  res.status(201).json({data:created,idempotent:false});
});

export const integrationHealth=asyncHandler(async(_req:any,res:any)=>{const [pending,failed,lastSuccessful]=await Promise.all([IntegrationEvent.countDocuments({status:{$in:['pending','processing']}}),IntegrationEvent.find({status:'failed'}).sort('-createdAt').limit(50).lean(),IntegrationEvent.findOne({status:'completed'}).sort('-processedAt').lean()]);res.json({data:{pending,failed,lastSuccessful:lastSuccessful?{eventId:lastSuccessful.eventId,type:lastSuccessful.type,processedAt:lastSuccessful.processedAt}:null}});});
export const retryEvent=asyncHandler(async(req:any,res:any)=>{const data=await IntegrationEvent.findByIdAndUpdate(req.params.id,{$set:{status:'pending',nextAttemptAt:new Date(),lastError:undefined}},{new:true});if(!data)throw new AppError(404,'Integration event not found');res.json({data});});
export const retryFailedEvents=asyncHandler(async(_req:any,res:any)=>{const result=await IntegrationEvent.updateMany({status:'failed'},{$set:{status:'pending',nextAttemptAt:new Date(),lastError:undefined}});res.json({data:{retried:result.modifiedCount}});});
export const fullMenuResync=asyncHandler(async(_req:any,res:any)=>{const [categories,items]=await Promise.all([Category.find().lean(),MenuItem.find().lean()]);for(const category of categories)await queueIntegrationEvent('CATEGORY_UPDATED',categoryDto(category));for(const item of items){const category:any=categories.find((value:any)=>String(value._id)===String(item.category));await queueIntegrationEvent('MENU_ITEM_UPDATED',menuItemDto(item,category?.externalId));}res.status(202).json({data:{categories:categories.length,menuItems:items.length}});});
